name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-push-kafcar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build kafcar
        run: ./gradlew bootBuildImage --imageName kafcar-app
