name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  e2e-tests-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
        working-directory: e2e-test
      - run: yarn run lint
        working-directory: e2e-test
