name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Start Kafka
        run: docker-compose -f docker-compose.tools.yml up -d

      - name: Start kafcar
        run: ./gradlew bootRun &

      - name: Run tests
        working-directory: e2e-test
        run: yarn install && yarn ci-test

      - name: Stopping Kafka
        run: docker-compose -f docker-compose.tools.yml down
